# Generated by Django 3.1.1 on 2022-06-20 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CategoryName', models.CharField(max_length=200)),
                ('Image', models.ImageField(default='https://cdn.wpmeducation.com/53544f/97c04745fa/default.jpg', upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ModelNo', models.CharField(max_length=200)),
                ('ProductImage', models.ImageField(default='https://cdn.wpmeducation.com/53544f/97c04745fa/default.jpg', upload_to='')),
                ('finish1', models.CharField(max_length=200)),
                ('fimage1', models.ImageField(default='https://cdn.wpmeducation.com/53544f/97c04745fa/default.jpg', upload_to='')),
                ('finish2', models.CharField(max_length=200)),
                ('fimage2', models.ImageField(default='https://cdn.wpmeducation.com/53544f/97c04745fa/default.jpg', upload_to='')),
                ('finish3', models.CharField(max_length=200)),
                ('fimage3', models.ImageField(default='https://cdn.wpmeducation.com/53544f/97c04745fa/default.jpg', upload_to='')),
                ('finish4', models.CharField(max_length=200)),
                ('fimage4', models.ImageField(default='https://cdn.wpmeducation.com/53544f/97c04745fa/default.jpg', upload_to='')),
                ('finish5', models.CharField(max_length=200)),
                ('fimage5', models.ImageField(default='https://cdn.wpmeducation.com/53544f/97c04745fa/default.jpg', upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='subcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SubCategoryName', models.CharField(max_length=200)),
                ('Image', models.ImageField(default='https://cdn.wpmeducation.com/53544f/97c04745fa/default.jpg', upload_to='')),
            ],
        ),
    ]
