# Generated by Django 3.1.1 on 2022-06-20 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barryinterior', '0002_auto_20220620_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='fimage1',
            field=models.ImageField(default='https://cdn.wpmeducation.com/53544f/97c04745fa/default.jpg', upload_to=None),
        ),
        migrations.AlterField(
            model_name='product',
            name='fimage2',
            field=models.ImageField(default='https://cdn.wpmeducation.com/53544f/97c04745fa/default.jpg', upload_to=None),
        ),
        migrations.AlterField(
            model_name='product',
            name='fimage3',
            field=models.ImageField(default='https://cdn.wpmeducation.com/53544f/97c04745fa/default.jpg', upload_to=None),
        ),
        migrations.AlterField(
            model_name='product',
            name='fimage4',
            field=models.ImageField(default='https://cdn.wpmeducation.com/53544f/97c04745fa/default.jpg', upload_to=None),
        ),
        migrations.AlterField(
            model_name='product',
            name='fimage5',
            field=models.ImageField(default='https://cdn.wpmeducation.com/53544f/97c04745fa/default.jpg', upload_to=None),
        ),
        migrations.AlterField(
            model_name='product',
            name='finish1',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='finish2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='finish3',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='finish4',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='finish5',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
