# Generated by Django 3.1.1 on 2022-06-20 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barryinterior', '0005_auto_20220620_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='fimage1',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='fimage2',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='fimage3',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='fimage4',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='fimage5',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
