# Generated by Django 3.1.1 on 2022-06-21 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('barryinterior', '0006_auto_20220620_1518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='fimage1',
        ),
        migrations.RemoveField(
            model_name='product',
            name='fimage2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='fimage3',
        ),
        migrations.RemoveField(
            model_name='product',
            name='fimage4',
        ),
        migrations.RemoveField(
            model_name='product',
            name='fimage5',
        ),
        migrations.RemoveField(
            model_name='product',
            name='finish1',
        ),
        migrations.RemoveField(
            model_name='product',
            name='finish2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='finish3',
        ),
        migrations.RemoveField(
            model_name='product',
            name='finish4',
        ),
        migrations.RemoveField(
            model_name='product',
            name='finish5',
        ),
        migrations.CreateModel(
            name='finish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FinisType', models.CharField(max_length=200)),
                ('FinishImage', models.ImageField(default='https://cdn.wpmeducation.com/53544f/97c04745fa/default.jpg', upload_to='')),
                ('ProductModelNo', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='barryinterior.product')),
            ],
        ),
    ]
