# Generated by Django 3.1.1 on 2022-06-21 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('barryinterior', '0007_auto_20220621_1002'),
    ]

    operations = [
        migrations.CreateModel(
            name='latestproduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(max_length=200)),
                ('product', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='barryinterior.product')),
            ],
        ),
    ]
