# Generated by Django 3.1.1 on 2022-06-21 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barryinterior', '0008_latestproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='inquiryDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Company', models.CharField(max_length=200)),
                ('Designation', models.CharField(max_length=200)),
                ('Address', models.TextField(max_length=800)),
                ('City', models.CharField(max_length=200)),
                ('Pincode', models.CharField(max_length=200)),
                ('State', models.CharField(max_length=200)),
                ('Country', models.CharField(max_length=200)),
                ('Mobile', models.IntegerField(max_length=200)),
                ('Telephone', models.IntegerField(max_length=200)),
                ('Email', models.CharField(max_length=200)),
                ('Comments', models.CharField(max_length=200)),
            ],
        ),
    ]
