# Generated by Django 3.1.1 on 2022-06-28 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barryinterior', '0013_gallery'),
    ]

    operations = [
        migrations.DeleteModel(
            name='latestproduct',
        ),
    ]
